name: procedural_puzzles
description: Offline procedural maze & puzzle generator with local saves
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  # Removed flutter_vibrate due to Android namespace build error

  # Optional: You can re-add haptics later with another package like `vibration: ^1.7.7`

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true